query getCampaginPostSearch($filter: GenericFilterRequestFundRaisingSearchReqInputType!) {
  fundRaisingSearchQueryHandler(filter: $filter) {
    listDto {
      items {
        id
      }
      count
    }
  }
}
