query getHashtagSearch($filter: GenericFilterRequestHashtagSearchReqInputType!) {
  hashtagSearchQueryHandler(filter: $filter) {
    listDto {
      items {
        id
        title
      }
      count
    }
  }
}
