query getHelpRelatedArticlesQuery($filter: GenericFilterRequestArticleRequestType!) {
  getHelpRelatedArticlesQuery(filter: $filter) {
    listDto {
      items {
        id
        title
        permalink
        categoryPermalink
        categoryTitle
        categoryIconUrl
        breadCrumb {
          id
          title
          parentId
          iconUrl
          permalink
          description
          articles {
            id
            title
            permalink
            categoryPermalink
            categoryTitle
            categoryIconUrl
            breadCrumb {
              id
              title
              parentId
              iconUrl
              permalink
              description
              articles {
                id
                title
                permalink
                categoryPermalink
                categoryTitle
                categoryIconUrl
                content
                titleTranslations {
                  key
                  value
                }
                contentTranslations {
                  key
                  value
                }
              }
              titleTranslations {
                key
                value
              }
              descriptionTranslations {
                key
                value
              }
            }
            content
            titleTranslations {
              key
              value
            }
            contentTranslations {
              key
              value
            }
          }
          titleTranslations {
            key
            value
          }
          descriptionTranslations {
            key
            value
          }
        }
        content
        titleTranslations {
          key
          value
        }
        contentTranslations {
          key
          value
        }
      }
      count
    }
    isSuccess
    responseExceptionStatus {
      message
      exceptionType
    }
    messagingKey
  }
}
