query getCertificates($filter: GenericFilterRequestCertificateGetAllInputType!) {
  getCertificates(filter: $filter) {
    listDto {
      items {
        id
        credentialDoesExpire
        issueDate
        expirationDate
        credentialID
        audience
        credentialUrl
        certificateName {
          id
          title
        }
        issuingOrganization {
          id
          title
        }
      }
    }
  }
}
