query getMedias($filter: GenericFilterRequestProjectMediasInputType!) {
  getMedias(filter: $filter) {
    listDto {
      items {
        id
        projectId
        url
        urls
      }
    }
  }
}
