query getPersonSkills($filter: GenericFilterRequestGetPersonSkillsInputType!) {
  getPersonSkills(filter: $filter) {
    listDto {
      items {
        id
        personId
        skill {
          id
          title
        }
        endorsementsCount
        endorsedByMe
        people {
          fullName
          avatarUrl
          headline
          firstName
          lastName
          id
          firstName
          lastName
        }
      }
    }
  }
}
