query getNumberRange($filter: GenericFilterRequestNumberRangeInputType!) {
  getNumberRanges(filter: $filter) {
    listDto {
      items {
        id
        from
        to
        desc
      }
    }
  }
}
