query getCampaignCategoriesQuery($filter: GenericFilterRequestCampaignCategoryReqType!) {
  getCampaignCategoriesQuery(filter: $filter) {
    listDto {
      items {
        id
        title
      }
      count
    }
  }
}
