query getCompanyForFilter($filter: GenericFilterRequestFilterReqInputType!) {
  companySearchQueryHandler(filter: $filter) {
    listDto {
      items {
        id
        title
      }
      count
    }
  }
}
