query getCollegeForFilter($filter: GenericFilterRequestEducationFilterReqInputType!) {
  collegeSearchQueryHandler(filter: $filter) {
    listDto {
      items {
        id
        title
      }
      count
    }
  }
}
