query getRangeForFilter($filter: GenericFilterRequestSearchNumberRangeInputType!) {
  getRangeQueryHandler(filter: $filter) {
    listDto {
      items {
        id
        from
        to
        desc
      }
      count
    }
  }
}
